# Autonomous-profile renderers
#
# Pure functions producing the config file contents baked into agent
# container images (dryvist/nix-agent-sandbox). Deliberately NOT a
# home-manager module: there must be no code path that renders these onto a
# host filesystem. Safety in this profile comes from the container boundary,
# scoped credentials, and default-deny egress — see profiles.nix.
#
# Consumed via the flake's `lib.renderAutonomous`.
{ lib }:

let
  profiles = import ./profiles.nix { inherit lib; };
  formatters = import ./formatters.nix { inherit lib; };
  inherit (profiles.autonomous) residualDeny;
in
{
  inherit residualDeny;

  # ~/.claude/settings.json inside the image. Launched as
  # `claude -p --bare --dangerously-skip-permissions`. Claude Code enforces
  # permissions.deny even under bypassPermissions, so the residual deny
  # list is real protection here, not decoration.
  claudeSettingsJson = builtins.toJSON {
    "$schema" = "https://json.schemastore.org/claude-code-settings.json";
    permissions = {
      allow = [ ];
      ask = [ ];
      deny = formatters.claude.formatShellCommands residualDeny;
      defaultMode = "bypassPermissions";
    };
  };

  # ~/.codex/config.toml inside the image. Launched as `codex exec`.
  # danger-full-access is correct, not careless: bwrap cannot nest inside an
  # unprivileged container, and the container is the sandbox.
  codexConfigToml = ''
    # Generated by nix-ai (autonomous profile). Do not use on a host:
    # this configuration assumes a container is the isolation boundary.
    approval_policy = "never"
    sandbox_mode = "danger-full-access"
  '';

  # Codex execpolicy rules carrying the residual deny list.
  codexRules = formatters.codex.formatRulesFile {
    allow = [ ];
    ask = [ ];
    deny = residualDeny;
  };

  # ~/.gemini/settings.json inside the image. Gemini's yolo posture is
  # primarily a launch flag (`--approval-mode yolo`); the settings file
  # disables Gemini's own container sandbox (we are already inside one) and
  # records the approval mode for tools that read it.
  geminiSettingsJson = builtins.toJSON {
    defaultApprovalMode = "yolo";
    tools = {
      sandbox = false;
    };
  };
}
