# Autonomous-profile renderers
#
# Pure functions producing the config file contents baked into agent
# container images (dryvist/nix-agent-sandbox). Deliberately NOT a
# home-manager module: there must be no code path that renders these onto a
# host filesystem. Safety in this profile comes from the container boundary,
# scoped credentials, and default-deny egress — see profiles.nix.
#
# SINGLE-LIST INHERITANCE: every tool's deny output derives from the one
# profiles.autonomous.residualDeny list, rendered through the same
# formatters the interactive home-manager modules use, in each tool's
# native spun-up format:
# - Claude:  permissions.deny in settings.json (modules/claude pipeline)
# - Codex:   execpolicy rules at .codex/rules/default.rules
#            (mirrors modules/codex/settings.nix)
# - Gemini:  Policy Engine TOML referenced via settings.json policyPaths
#            (mirrors modules/antigravity-cli/settings.nix)
#
# Consumed via the flake's `lib.renderAutonomous`.
{
  lib,
  homeDir ? "/home/agent",
}:

let
  profiles = import ./profiles.nix { inherit lib; };
  formatters = import ./formatters.nix { inherit lib; };
  inherit (profiles.autonomous) residualDeny;

  # The one permission set all autonomous renderers inherit from.
  residualDenyPermissions = {
    allow = [ ];
    ask = [ ];
    deny = residualDeny;
  };

  geminiPolicyPath = "${homeDir}/.gemini/policies/autonomous.toml";

  # JSON string literals are valid TOML strings; numbers render bare.
  tomlStr = builtins.toJSON;
  renderGeminiRule = rule: ''
    [[rule]]
    toolName = ${tomlStr rule.toolName}
    commandPrefix = ${tomlStr rule.commandPrefix}
    decision = ${tomlStr rule.decision}
    priority = ${toString rule.priority}
    denyMessage = ${tomlStr rule.denyMessage}
  '';

  # ~/.claude/settings.json inside the image. Launched as
  # `claude -p --bare --dangerously-skip-permissions`. Claude Code enforces
  # permissions.deny even under bypassPermissions, so the residual deny
  # list is real protection here, not decoration.
  claudeSettingsJson = builtins.toJSON {
    "$schema" = "https://json.schemastore.org/claude-code-settings.json";
    permissions = {
      allow = [ ];
      ask = [ ];
      deny = formatters.claude.formatDenied residualDenyPermissions;
      defaultMode = "bypassPermissions";
    };
  };

  # ~/.codex/config.toml inside the image. Launched as `codex exec`.
  # danger-full-access is correct, not careless: bwrap cannot nest inside an
  # unprivileged container, and the container is the sandbox.
  codexConfigToml = ''
    # Generated by nix-ai (autonomous profile). Do not use on a host:
    # this configuration assumes a container is the isolation boundary.
    approval_policy = "never"
    sandbox_mode = "danger-full-access"
  '';

  # ~/.codex/rules/default.rules — same path the interactive codex module
  # deploys to, carrying the same residual deny list.
  codexRules = formatters.codex.formatRulesFile residualDenyPermissions;

  # ~/.gemini/settings.json inside the image. Policy Engine TOML referenced
  # via `policyPaths`; the CLI's own container sandbox is disabled because we
  # are already inside one.
  #
  # `general.defaultApprovalMode = "yolo"` is deliberately NOT set. Verified
  # live on gemini-cli 0.53: the key does not merely get ignored, the CLI
  # hard-errors and refuses to start —
  #   Invalid enum value. Expected 'default' | 'auto_edit' | 'plan',
  #   received 'yolo'
  # so rendering it would break the tool this file configures. The autonomous
  # posture is carried at launch instead (`--dangerously-skip-permissions` for
  # agy, which superseded gemini-cli here after Google terminated individual
  # OAuth on it). That launch flag is the documented exception to the
  # otherwise filesystem-only rule.
  #
  # `security.auth.selectedType` is pinned so a headless run does not stop at
  # the interactive auth picker.
  geminiSettingsJson = builtins.toJSON {
    "$schema" =
      "https://raw.githubusercontent.com/google-gemini/gemini-cli/main/schemas/settings.schema.json";
    policyPaths = [ geminiPolicyPath ];
    security = {
      auth = {
        selectedType = "oauth-personal";
      };
    };
    tools = {
      sandbox = false;
    };
  };

  # Policy Engine TOML: deny rules (priority 200) override yolo approval,
  # so the residual deny holds even in fully-autonomous mode.
  geminiPolicyToml = ''
    # Generated by nix-ai (autonomous profile).
  ''
  + lib.concatMapStrings renderGeminiRule (formatters.gemini.formatDenyRules residualDenyPermissions);
in
{
  inherit
    residualDeny
    claudeSettingsJson
    codexConfigToml
    codexRules
    geminiSettingsJson
    geminiPolicyToml
    ;

  # Home-relative path -> contents, ready for an image builder to bake
  # under ${homeDir}. One attrset so image builds cannot forget a file.
  files = {
    ".claude/settings.json" = claudeSettingsJson;
    ".codex/config.toml" = codexConfigToml;
    ".codex/rules/default.rules" = codexRules;
    ".gemini/settings.json" = geminiSettingsJson;
    ".gemini/policies/autonomous.toml" = geminiPolicyToml;
  };
}
