# Antigravity Components
#
# Manages custom commands for Antigravity CLI.
# Custom commands are auto-generated from shared Markdown definitions.
{
  config,
  lib,
  ai-assistant-instructions,
  ...
}:

let
  cfg = config.programs.antigravity-cli;

  # ── Commands (from flake inputs) ───────────────────────────────────

  mkCommandFiles =
    components:
    builtins.listToAttrs (
      map (c: {
        name = ".gemini/antigravity-cli/commands/${c.name}.toml";
        value = {
          inherit (c) source;
          force = true;
        };
      }) components
    );

  mkLocalCommands =
    locals:
    lib.mapAttrs' (
      name: path:
      lib.nameValuePair ".gemini/antigravity-cli/commands/${name}.toml" {
        source = path;
        force = true;
      }
    ) locals;

  # ── Auto-generated commands from shared Markdown definitions ───────
  # Reads from ai-assistant-instructions/agentsmd/commands/*.md
  # and generates Antigravity TOML command files.

  commandsDir = "${ai-assistant-instructions}/agentsmd/commands";

  processCommandFile =
    fileName:
    let
      filePath = "${commandsDir}/${fileName}";
      fileContent = builtins.readFile filePath;

      lines = lib.splitString "\n" fileContent;
      lineCount = builtins.length lines;

      secondDelimIndex =
        let
          find =
            idx:
            if idx >= lineCount then
              null
            else if lib.trim (builtins.elemAt lines idx) == "---" then
              idx
            else
              find (idx + 1);
        in
        find 1;

      hasFrontmatter =
        lineCount >= 3 && lib.trim (builtins.elemAt lines 0) == "---" && secondDelimIndex != null;

      frontmatterRaw =
        if hasFrontmatter then
          lib.concatStringsSep "\n" (lib.sublist 1 (secondDelimIndex - 1) lines)
        else
          "";

      contentRaw =
        if hasFrontmatter then
          lib.concatStringsSep "\n" (
            lib.sublist (secondDelimIndex + 1) (lineCount - secondDelimIndex - 1) lines
          )
        else
          fileContent;

      descLine = lib.findFirst (l: lib.hasPrefix "description:" (lib.trim l)) null (
        lib.splitString "\n" frontmatterRaw
      );

      description =
        if descLine != null then
          lib.trim (lib.removePrefix "description:" (lib.trim descLine))
        else
          "Custom command generated from ${fileName}";

      safeDescription = lib.replaceStrings [ "\\" "\"" ] [ "\\\\" "\\\"" ] description;
      safeContent = lib.replaceStrings [ "\"\"\"" ] [ "\"\"\\\"" ] (lib.trim contentRaw);

      tomlContent = ''
        description = "${safeDescription}"
        prompt = """
        ${safeContent}
        """
      '';

      outName = lib.replaceStrings [ ".md" ] [ ".toml" ] fileName;
    in
    {
      name = ".gemini/antigravity-cli/commands/${outName}";
      value = {
        text = tomlContent;
        force = true;
      };
    };

  commandFiles =
    if builtins.pathExists commandsDir then
      builtins.attrNames (
        lib.filterAttrs (n: v: v == "regular" && lib.hasSuffix ".md" n) (builtins.readDir commandsDir)
      )
    else
      [ ];

  autoGeneratedCommands = builtins.listToAttrs (map processCommandFile commandFiles);

in
{
  config = lib.mkIf cfg.enable {
    home.file =
      # Explicit commands (from flake inputs and local)
      mkCommandFiles cfg.commands.fromFlakeInputs
      // mkLocalCommands cfg.commands.local
      # Auto-generated commands from agentsmd
      // autoGeneratedCommands;
  };
}
