# GitHub Copilot CLI Configuration
#
# Returns home.file entries for GitHub Copilot CLI.
# Imported by home.nix for clean separation of AI CLI configs.
#
# Strategy: Directory trust model with runtime permission flags
#
# Configuration format:
# - config.json: Contains trusted_folders array
# - CLI flags: --allow-tool and --deny-tool (runtime only)
#
# Note: Unlike Claude/Gemini, Copilot's permission system is primarily
# CLI-flag based. The config file only manages directory trust.

{
  config,
  lib,
  pkgs,
  nix-claude-code,
  ...
}:

let
  copilotAllow = import ./permissions/copilot-permissions-allow.nix {
    inherit config lib nix-claude-code;
  };

  # Copilot settings object
  settings = {
    # Trusted directories where Copilot can operate without confirmation
    inherit (copilotAllow) trusted_folders;

    # Additional Copilot CLI settings can be added here
    # Note: Tool-level permissions require CLI flags, not config settings
  };

  # Generate pretty-printed JSON using a derivation with jq
  # This improves readability for debugging and matches Claude's format
  settingsJson =
    pkgs.runCommand "copilot-config.json"
      {
        nativeBuildInputs = [ pkgs.jq ];
        json = builtins.toJSON settings;
        passAsFile = [ "json" ];
      }
      ''
        jq '.' "$jsonPath" > $out
      '';
in
{
  ".copilot/config.json".source = settingsJson;

  # Copilot CLI has no native skill loader; global custom instructions point
  # it at the shared skill manifest generated by modules/agent-skills.
  ".copilot/copilot-instructions.md".text = ''
    Reusable agent skills live in `~/.agents/skills/<name>/SKILL.md`.
    Consult `~/.agents/skills/INDEX.md` and follow a skill when it matches the task.
  '';
}
