# Codex Formatter
#
# Codex uses native config.toml keys for sandbox/approval defaults and optional
# execpolicy `.rules` files for command-prefix decisions outside the sandbox.
{ lib, flattenCommands }:

let
  tokenizeCommand = cmd: lib.filter (token: token != "") (lib.splitString " " cmd);

  tokenIsRepresentable =
    token:
    !(lib.any (char: lib.hasInfix char token) [
      "*"
      "?"
      "<"
      ">"
      "|"
      "&"
      ";"
      "$"
      "("
      ")"
      "{"
      "}"
      "\""
      "'"
      "\\"
      "`"
      "~"
    ]);

  commandIsRepresentable =
    cmd:
    let
      tokens = tokenizeCommand cmd;
    in
    tokens != [ ] && lib.all tokenIsRepresentable tokens;

  supportedCommands = cmds: lib.filter commandIsRepresentable cmds;

  skippedCommands =
    cmds:
    let
      supported = supportedCommands cmds;
    in
    builtins.length cmds - builtins.length supported;

  formatPrefixRule =
    decision: cmd: "prefix_rule(${builtins.toJSON (tokenizeCommand cmd)}, ${builtins.toJSON decision})";

  renderRules =
    decision: cmds:
    let
      supported = supportedCommands cmds;
    in
    lib.concatMapStringsSep "\n" (cmd: formatPrefixRule decision cmd) supported;
in
{
  inherit tokenizeCommand commandIsRepresentable supportedCommands;

  formatRulesFile =
    permissions:
    let
      allowCommands = flattenCommands permissions.allow;
      askCommands = flattenCommands permissions.ask;
      denyCommands = flattenCommands permissions.deny;
      skippedTotal =
        skippedCommands allowCommands + skippedCommands askCommands + skippedCommands denyCommands;

      allowRules = renderRules "allow" allowCommands;
      askRules = renderRules "prompt" askCommands;
      denyRules = renderRules "forbidden" denyCommands;
    in
    ''
      # Generated by nix-ai from ai-assistant-instructions/agentsmd/permissions/.
      # These rules apply to commands outside Codex's filesystem sandbox.
      # Unsupported shell-only patterns were skipped: ${toString skippedTotal}

      ${denyRules}

      ${askRules}

      ${allowRules}
    '';
}
