#!/usr/bin/env python3
"""Apply / set / clear the runtime override for the "default" model role.

The declared default comes from Nix (programs.mlx.defaultModelKey) and lands in
the base llama-swap config. This script re-points the "default" alias in the
MUTABLE runtime config at a different CATALOG KEY without a rebuild; llama-swap
runs with --watch-config, so a write is picked up immediately.

Never physical model ids: the override file names a catalog key, and the
key -> physical map is generated by Nix alongside the config.

The override is LOUD by design. `apply` prints a banner whenever an override is
in effect, and an unusable override prints an error and falls back to the
declared key rather than leaving the config with no default.

Environment:
  MLX_LLAMA_SWAP_CONFIG        mutable runtime llama-swap config (JSON)
  MLX_DEFAULT_MODEL_KEYMAP     Nix-generated {"declared":key|null,"keys":{...}}
  MLX_DEFAULT_MODEL_OVERRIDE   override file holding one catalog key

Subcommands: apply | set <key> | clear | show
"""

import json
import os
import sys
import tempfile
from pathlib import Path

ALIAS = "default"


def _env_path(name: str) -> Path:
    value = os.environ.get(name)
    if not value:
        print(f"ERROR: {name} is not set", file=sys.stderr)
        sys.exit(2)
    return Path(value)


def _load_keymap() -> tuple[str | None, dict[str, str]]:
    data = json.loads(_env_path("MLX_DEFAULT_MODEL_KEYMAP").read_text())
    return data.get("declared"), data.get("keys", {})


def _physical(keys: dict[str, str], key: str | None) -> str:
    """Physical id for ``key``, or a marker. Takes None so callers need no cast."""
    return keys.get(key, "(unset)") if key is not None else "(unset)"


def _read_override() -> str | None:
    path = _env_path("MLX_DEFAULT_MODEL_OVERRIDE")
    if not path.is_file():
        return None
    return path.read_text().strip() or None


def _write_json(target: Path, data: dict) -> None:
    fd, tmp = tempfile.mkstemp(dir=target.parent, prefix=target.name + ".", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as f:
            json.dump(data, f, indent=2)
            f.write("\n")
        os.chmod(tmp, 0o600)
        os.replace(tmp, target)
    except Exception:
        if os.path.exists(tmp):
            os.unlink(tmp)
        raise


def _reject(key: str, keys: dict[str, str], models: dict) -> str | None:
    """Return why ``key`` cannot serve the default alias, or None if it can."""
    if key not in keys:
        return f"not a catalog key (known: {', '.join(sorted(keys)) or 'none'})"
    if keys[key] not in models:
        return f"catalog key resolves to {keys[key]}, which has no llama-swap backend"
    return None


def _repoint(config: dict, physical: str) -> bool:
    """Move the default alias onto ``physical``. True when the file changed."""
    changed = False
    for model_id, entry in config.get("models", {}).items():
        aliases = list(entry.get("aliases", []))
        if model_id == physical:
            # Append only when absent, so a no-op apply leaves the file (and
            # its mtime) alone — llama-swap --watch-config reloads on write.
            wanted = aliases if ALIAS in aliases else aliases + [ALIAS]
        else:
            wanted = [a for a in aliases if a != ALIAS]
        if wanted != aliases:
            entry["aliases"] = wanted
            changed = True
    return changed


def cmd_apply() -> None:
    config_path = _env_path("MLX_LLAMA_SWAP_CONFIG")
    declared, keys = _load_keymap()
    config = json.loads(config_path.read_text())
    models = config.get("models", {})

    effective = declared
    override = _read_override()
    if override is not None:
        reason = _reject(override, keys, models)
        if reason:
            print(
                f"ERROR: default-model override {override!r} is unusable: {reason}. "
                f"Falling back to the declared default {declared!r}. "
                f"Clear it with: mlx-default-model clear",
                file=sys.stderr,
            )
        else:
            effective = override
            print(
                "=" * 72
                + f"\nMLX DEFAULT MODEL OVERRIDE ACTIVE\n"
                + f"  declared (Nix): {declared} -> {_physical(keys, declared)}\n"
                + f"  override (run): {override} -> {keys[override]}\n"
                + "  clear with: mlx-default-model clear\n"
                + "=" * 72
            )

    if effective is None:
        # No defaultModelKey declared. That is a normal, supported config: the
        # "default" alias then comes from a catalog entry's own roles list and
        # this script must leave it alone. What is NOT normal is no model
        # holding the alias at all — every caller asking for "default" 404s —
        # so distinguish the two rather than sharing one bare return.
        if not any(ALIAS in e.get("aliases", []) for e in models.values()):
            print(
                'ERROR: no model holds the "default" alias and no '
                "programs.mlx.defaultModelKey is declared — every request for "
                '"default" will 404. Set defaultModelKey, or give a catalog '
                'entry roles = [ "default" ].',
                file=sys.stderr,
            )
        return
    if effective not in keys:
        # Only reachable if the DECLARED key is absent from its own keymap,
        # which the Nix assertions forbid — so it means the keymap is stale.
        print(
            f"ERROR: declared default {effective!r} is not in the keymap; "
            f"the llama-swap config was left unchanged. Re-run darwin-rebuild.",
            file=sys.stderr,
        )
        return
    if _repoint(config, keys[effective]):
        _write_json(config_path, config)


def cmd_set(key: str) -> None:
    config_path = _env_path("MLX_LLAMA_SWAP_CONFIG")
    _declared, keys = _load_keymap()
    models = json.loads(config_path.read_text()).get("models", {})
    reason = _reject(key, keys, models)
    if reason:
        print(f"ERROR: cannot set default to {key!r}: {reason}", file=sys.stderr)
        sys.exit(1)
    _env_path("MLX_DEFAULT_MODEL_OVERRIDE").write_text(key + "\n")
    cmd_apply()


def cmd_clear() -> None:
    path = _env_path("MLX_DEFAULT_MODEL_OVERRIDE")
    if path.exists():
        path.unlink()
        print(f"Cleared default-model override (was: {path})")
    cmd_apply()


def cmd_show() -> None:
    declared, keys = _load_keymap()
    override = _read_override()
    print(f"declared (Nix): {declared or '(none)'} -> {_physical(keys, declared)}")
    if override is None:
        print("override:       none — serving the declared default")
        return
    models = json.loads(_env_path("MLX_LLAMA_SWAP_CONFIG").read_text()).get("models", {})
    reason = _reject(override, keys, models)
    if reason:
        print(f"override:       {override} — UNUSABLE ({reason}); declared is served")
        return
    print(f"override:       {override} -> {keys[override]}  <== ACTIVE, overriding Nix")


def main() -> None:
    argv = sys.argv[1:]
    if argv[:1] == ["apply"] and len(argv) == 1:
        cmd_apply()
    elif argv[:1] == ["set"] and len(argv) == 2:
        cmd_set(argv[1])
    elif argv[:1] == ["clear"] and len(argv) == 1:
        cmd_clear()
    elif argv[:1] == ["show"] and len(argv) == 1:
        cmd_show()
    else:
        print("Usage: mlx-default-model {apply|set <key>|clear|show}", file=sys.stderr)
        sys.exit(2)


if __name__ == "__main__":
    main()
